#############################################################################
# Makefile for building: bin/Fractal
# Generated by qmake (2.01a) (Qt 4.8.7) on: pon. maj 20 10:15:07 2019
# Project:  Fractal.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Fractal.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		FComplex.cpp \
		Polynomial.cpp \
		Julia.cpp \
		CustomGraphics.cpp \
		CustomSpinner.cpp \
		FrontForm.cpp moc_CustomGraphics.cpp \
		moc_CustomSpinner.cpp \
		moc_FrontForm.cpp
OBJECTS       = main.o \
		FComplex.o \
		Polynomial.o \
		Julia.o \
		CustomGraphics.o \
		CustomSpinner.o \
		FrontForm.o \
		moc_CustomGraphics.o \
		moc_CustomSpinner.o \
		moc_FrontForm.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Fractal.pro
QMAKE_TARGET  = Fractal
DESTDIR       = bin/
TARGET        = bin/Fractal

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_front.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Fractal.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Fractal.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Fractal.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Fractal1.0.0 || $(MKDIR) .tmp/Fractal1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Fractal1.0.0/ && $(COPY_FILE) --parents FComplex.h Polynomial.h Julia.h CustomGraphics.h CustomSpinner.h FrontForm.h .tmp/Fractal1.0.0/ && $(COPY_FILE) --parents main.cpp FComplex.cpp Polynomial.cpp Julia.cpp CustomGraphics.cpp CustomSpinner.cpp FrontForm.cpp .tmp/Fractal1.0.0/ && $(COPY_FILE) --parents front.ui .tmp/Fractal1.0.0/ && (cd `dirname .tmp/Fractal1.0.0` && $(TAR) Fractal1.0.0.tar Fractal1.0.0 && $(COMPRESS) Fractal1.0.0.tar) && $(MOVE) `dirname .tmp/Fractal1.0.0`/Fractal1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Fractal1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_CustomGraphics.cpp moc_CustomSpinner.cpp moc_FrontForm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_CustomGraphics.cpp moc_CustomSpinner.cpp moc_FrontForm.cpp
moc_CustomGraphics.cpp: Julia.h \
		Polynomial.h \
		FComplex.h \
		CustomGraphics.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) CustomGraphics.h -o moc_CustomGraphics.cpp

moc_CustomSpinner.cpp: CustomSpinner.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) CustomSpinner.h -o moc_CustomSpinner.cpp

moc_FrontForm.cpp: Julia.h \
		Polynomial.h \
		FComplex.h \
		ui_front.h \
		CustomGraphics.h \
		CustomSpinner.h \
		FrontForm.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) FrontForm.h -o moc_FrontForm.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_front.h
compiler_uic_clean:
	-$(DEL_FILE) ui_front.h
ui_front.h: front.ui \
		CustomGraphics.h \
		CustomSpinner.h \
		Julia.h \
		Polynomial.h \
		FComplex.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic front.ui -o ui_front.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp FrontForm.h \
		Julia.h \
		Polynomial.h \
		FComplex.h \
		ui_front.h \
		CustomGraphics.h \
		CustomSpinner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

FComplex.o: FComplex.cpp FComplex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FComplex.o FComplex.cpp

Polynomial.o: Polynomial.cpp Polynomial.h \
		FComplex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Polynomial.o Polynomial.cpp

Julia.o: Julia.cpp Julia.h \
		Polynomial.h \
		FComplex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Julia.o Julia.cpp

CustomGraphics.o: CustomGraphics.cpp CustomGraphics.h \
		Julia.h \
		Polynomial.h \
		FComplex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CustomGraphics.o CustomGraphics.cpp

CustomSpinner.o: CustomSpinner.cpp CustomSpinner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CustomSpinner.o CustomSpinner.cpp

FrontForm.o: FrontForm.cpp FrontForm.h \
		Julia.h \
		Polynomial.h \
		FComplex.h \
		ui_front.h \
		CustomGraphics.h \
		CustomSpinner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FrontForm.o FrontForm.cpp

moc_CustomGraphics.o: moc_CustomGraphics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CustomGraphics.o moc_CustomGraphics.cpp

moc_CustomSpinner.o: moc_CustomSpinner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CustomSpinner.o moc_CustomSpinner.cpp

moc_FrontForm.o: moc_FrontForm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FrontForm.o moc_FrontForm.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

